#include "Parameters.h"

const char* ParameterIds[Parameter::COUNT] = {
    "Interpolation",
    "HighCutEnabled",
    "LowCutEnabled",
    "InputMix",
    "HighCut",
    "LowCut",
    "DryOut",
    "EarlyOut",
    "LateOut",

    "TapEnabled",
    "TapCount",
    "TapDecay",
    "TapPredelay",
    "TapLength",

    "EarlyDiffuseEnabled",
    "EarlyDiffuseCount",
    "EarlyDiffuseDelay",
    "EarlyDiffuseModAmount",
    "EarlyDiffuseFeedback",
    "EarlyDiffuseModRate",

    "LateMode",
    "LateLineCount",
    "LateDiffuseEnabled",
    "LateDiffuseCount",
    "LateLineSize",
    "LateLineModAmount",
    "LateDiffuseDelay",
    "LateDiffuseModAmount",
    "LateLineDecay",
    "LateLineModRate",
    "LateDiffuseFeedback",
    "LateDiffuseModRate",

    "EqLowShelfEnabled",
    "EqHighShelfEnabled",
    "EqLowpassEnabled",
    "EqLowFreq",
    "EqHighFreq",
    "EqCutoff",
    "EqLowGain",
    "EqHighGain",
    "EqCrossSeed",

    "SeedTap",
    "SeedDiffusion",
    "SeedDelay",
    "SeedPostDiffusion",
};

const char* ParameterLabel[Parameter::COUNT] = {
    "Interpolation",
    "High Cut",
    "Low Cut",
    "Input Mix",
    "High Cut",
    "Low Cut",
    "Dry Out",
    "Early Out",
    "Late Out",

    "Multitap Enabled",
    "Count",
    "Decay",
    "Pre-delay",
    "Length",

    "Diffusion",
    "Diffusion Stages",
    "Delay",
    "Mod Amt",
    "Feedback",
    "Mod Rate",

    "Mode",
    "Line Count",
    "Diffusion",
    "Diffusion Stages",
    "Size",
    "Mod Amt",
    "Delay",
    "Mod Amt",
    "Decay",
    "Mod Rate",
    "Feedback",
    "Mod Rate",

    "Low Shelf",
    "High Shelf",
    "Lowpass",
    "Low Freq",
    "High Freq",
    "Cutoff",
    "Low Gain",
    "High Gain",
    "Cross Seed",

    "Tap Seed",
    "Diffusion Seed",
    "Delay Seed",
    "Late Diffusion Seed",
};

const char* ParameterSuffix[Parameter::COUNT] = {
    "", // Interpolation,
    "", // HighCutEnabled,
    "", // LowCutEnabled,
    "%", // InputMix,
    "Hz", // HighCut,
    "Hz", // LowCut,
    "dB", // DryOut,
    "dB", // EarlyOut,
    "dB", // LateOut,

    "", // TapEnabled,
    "", // TapCount,
    "ms", // TapDecay,
    "ms", // TapPredelay,
    "ms", // TapLength,

    "", // EarlyDiffuseEnabled,
    "", // EarlyDiffuseCount,
    "ms", // EarlyDiffuseDelay,
    "%", // EarlyDiffuseModAmount,
    "%", // EarlyDiffuseFeedback,
    "Hz", // EarlyDiffuseModRate,

    "", // LateMode,
    "", // LateLineCount,
    "", // LateDiffuseEnabled,
    "", // LateDiffuseCount,
    "ms", // LateLineSize,
    "%", // LateLineModAmount,
    "ms", // LateDiffuseDelay,
    "%", // LateDiffuseModAmount,
    "sec", // LateLineDecay,
    "Hz", // LateLineModRate,
    "%", // LateDiffuseFeedback,
    "Hz", // LateDiffuseModRate,

    "", // EqLowShelfEnabled,
    "", // EqHighShelfEnabled,
    "", // EqLowpassEnabled,
    "Hz", // EqLowFreq,
    "Hz", // EqHighFreq,
    "Hz", // EqCutoff,
    "dB", // EqLowGain,
    "dB", // EqHighGain,
    "%", // EqCrossSeed,

    "", //SeedTap,
    "", //SeedDiffusion,
    "", //SeedDelay,
    "", //SeedPostDiffusion,
};
